# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: argocd-secret
#   namespace: argocd
# spec:
#   refreshInterval: 24h
#   secretStoreRef:
#     # kind: SecretStore
#     kind: ClusterSecretStore
#     name: ops-azure-store
#   target:
#     name: argocd-secret
#     creationPolicy: Merge
#     template:
#       type: Opaque
#       data:
#         oidc.azure.clientSecret: "{{ `{{ .ArgoSsoClientSecret }}` }}"
#         oidc.azure.clientId: "{{ `{{ .ArgoSsoClientId }}` }}"
#   dataFrom:
#   - find:
#       conversionStrategy: Default
#       decodingStrategy: None
#       name:
#         regexp: "^ArgoSsoClient"
#       tags:
#         envType: "{{ .Values.envType }}"
# # ---
# # apiVersion: external-secrets.io/v1beta1
# # kind: ExternalSecret
# # metadata:
# #   name: argocd-server-admin-password
# #   namespace: argocd
# # spec:
# #   refreshInterval: 24h
# #   secretStoreRef:
# #     # kind: SecretStore
# #     kind: ClusterSecretStore
# #     name: demo-services-azure-store
# #   target:
# #     name: argocd-secret
# #     creationPolicy: Merge
# #     template:
# #       type: Opaque
# #       data:
# #         admin.password: '{{ (printf "%s" (bcrypt `{{ .ArgocdAdminPassword }}` )) }}'
# #   dataFrom:
# #   - find:
# #       conversionStrategy: Default
# #       decodingStrategy: None
# #       tags:
# #         type: "argocd"
# {{- end }}
