# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   generation: 1
#   name: default
#   namespace: argocd
# spec:
#   sourceRepos: []
#   sourceNamespaces: []
#   destinations: []
#   namespaceResourceBlacklist:
#     - group: "*"
#       kind: "*"

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'