apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 1
  name: default
  namespace: argocd
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
    - group: "*"
      kind: "*"