apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend
  namespace: argocd
spec:
  description: Frontend Project
  destinations:
    - namespace: 'frontend'
      server: 'https://10.97.45.162:443'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
#  namespaceResourceBlacklist:
#    - group: 'argoproj.io'
#      kind: Application
#    - group: 'argoproj.io'
#      kind: ApplicationSet
#    - group: namespaceResourceBlacklist
#      kind: AppProject
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceBlacklist:
    - group: 'argoproj.io'
      kind: Application
    - group: 'argoproj.io'
      kind: ApplicationSet
    - group: namespaceResourceBlacklist
      kind: AppProject
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
  sourceRepos:
    - git@github.com:moaaznoaman/argocd.git
    - git@github.com:moaaznoaman/argocd-variables.git
    - git@github.com:moaaznoaman/argocd-variables-new.git