apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret-creds
  namespace: "{{ .Values.envType }}" # default
spec:
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: "{{ .Values.env }}ArgocdClient.*"
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend # argocd-backend
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: argocd-secret-creds
    template:
      data:
        oidc.azure.clientId: '{{ printf "{{ .%sArgocdClientId }}" .Values.env }}'
        oidc.azure.clientSecret: '{{ printf "{{ .%sArgocdClientSecret }}" .Values.env }}'
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque