apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-k8s-secret-password
  namespace: prod
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 60s
  secretStoreRefs:
    - name: vault-backend-secretstore
      kind: SecretStore
  selector:
    secret:
      name: k8s-secret
  data:
    - conversionStrategy: None
      match:
        secretKey: password
        remoteRef:
          remoteKey: password
          property: password