apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: default
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret-k8s
  data:
    - secretKey: SECRET
      remoteRef:
        key: test/
        property: key
# dataFrom:
#    - extract:
#        key: test-eso/test-secret