---
apiVersion: v2
name: monitoring
version: 1.0.0

dependencies:
  - name: promtail
    version: 6.16.6
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled
  - name: loki
    version: 6.29.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
