apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - { key: "env", operator: In, values: [ "test" ] }
  template:
    metadata:
      name: "backend-{{.name}}"
      namespace: argocd
      labels:
        env: "{{ .metadata.labels.env }}"
        app: "infra"
    spec:
      project: backend
      sources:
        - repoURL: git@github.com:moaaznoaman/argocd-variables.git
          targetRevision: "{{ .metadata.labels.envBranch }}"
          ref: values
        - repoURL: git@github.com:moaaznoaman/argocd-variables-new.git
          targetRevision: HEAD
          ref: valuesnew
        - repoURL: git@github.com:moaaznoaman/argocd.git
          path: charts/backend
          targetRevision: HEAD
          helm:
            valueFiles:
              - "values.yaml"
              - "$values/environments/backend/values.yaml"
#              - "$valuesnew/environments/backend/values.yaml"
      destination:
        name: "{{.name}}" # "{{ .metadata.labels.name }}" # https://kubernetes.default.svc
        namespace: "backend"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        #   - ServerSideApply=true # Big CRDs.
        #   - ApplyOutOfSyncOnly=true
        #   - preserveResourcesOnDeletion=true