apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend-secretstore
  namespace: default
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "myk8ssecret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
#         kubernetes:
#           mountPath: "vcluster-1"
#           role: "external-secrets"