{
 "title": "Payment Processor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "payment_processor",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster='cb'}, cluster)"
    }
   },
   {
    "name": "env_currency_factor",
    "query": {
     "query": "label_values(env_info, currency_factor)"
    }
   },
   {
    "name": "env_currency_iso",
    "query": {
     "query": "label_values(env_info, currency_iso)"
    }
   },
   {
    "name": "fsp_namespace",
    "label": "FSP",
    "query": {
     "query": "label_values(up{container=\"payment-processor\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "env_info",
     "legendFormat": "{{ title }} (PP $fsp_namespace)"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bank requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "yaxes": [
    { "format": "req" }
   ],
   "targets": [
    {
     "expr": "sum by (job, code_group, route) (rate(payment_processor_requests_total{cluster=\"$fsp_namespace\"}[$__rate_interval])) * 120",
     "legendFormat": "{{route}} {{code_group}}"
    }
   ]
  },
  {
   "title": "Bank 90% Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {},
    {
     "expr": "histogram_quantile(\n    0.90, \n    sum without (container,namespace,instance) (irate(payment_processor_request_duration_bucket{cluster=\"$fsp_namespace\"}[$__rate_interval])))",
     "legendFormat": "{{job}}/{{route}}"
    }
   ]
  },
  {
   "title": "Bank Average latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(payment_processor_request_duration_sum{cluster=\"$fsp_namespace\"}[$__rate_interval]) / rate(payment_processor_request_duration_count[$__rate_interval])",
     "legendFormat": "{{job}}/{{route}}"
    }
   ]
  },
  {
   "title": "Transfer times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(payment_processor_transfer_time_sum{cluster=\"$fsp_namespace\"}[$__rate_interval]) / rate(payment_processor_transfer_time_count{cluster=\"$fsp_namespace\"}[$__rate_interval])",
     "legendFormat": "{{direction}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent per Transfer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(payment_processor_db_operation_sum{cluster=\"$fsp_namespace\"}[$__rate_interval])) / (sum(rate(payment_processor_transfer_time_count{cluster=\"$fsp_namespace\",direction=\"transfer\"}[$__rate_interval])) > 0 or vector(1))",
     "legendFormat": "DB operations"
    },
    {
     "expr": "sum(rate(payment_processor_message_queue_send_sum{cluster=\"$fsp_namespace\"}[$__rate_interval])) / (sum(rate(payment_processor_transfer_time_count{cluster=\"$fsp_namespace\",direction=\"transfer\"}[$__rate_interval])) > 0 or vector(1))",
     "legendFormat": "Servicebus send"
    },
    {
     "expr": "sum(rate(payment_processor_verifier_request_duration_sum{cluster=\"$fsp_namespace\"}[$__rate_interval])) / (sum(rate(payment_processor_transfer_time_count{cluster=\"$fsp_namespace\",direction=\"transfer\"}[$__rate_interval])) > 0 or vector(1))",
     "legendFormat": "Verifier"
    },
    {}
   ]
  },
  {
   "title": "Database operation times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(payment_processor_db_operation_sum{cluster=\"$fsp_namespace\"}[$__rate_interval]) / rate(payment_processor_db_operation_count{cluster=\"$fsp_namespace\"}[$__rate_interval])",
     "legendFormat": "{{tx}}"
    }
   ]
  },
  {
   "title": "Message Bus Send Operation Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(payment_processor_message_queue_send_sum{cluster=\"$fsp_namespace\"}[$__rate_interval]) / rate(payment_processor_message_queue_send_count{cluster=\"$fsp_namespace\"}[$__rate_interval])",
     "legendFormat": "message bus"
    }
   ]
  },
  {
   "title": "Verifier Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(payment_processor_verifier_request_duration_sum{cluster=\"$fsp_namespace\"}[$__rate_interval]) / rate(payment_processor_verifier_request_duration_count{cluster=\"$fsp_namespace\"}[$__rate_interval])",
     "legendFormat": "verifier"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$fsp_namespace\",container=\"payment-processor\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster=\"$fsp_namespace\",container=\"payment-processor\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(payment_processor_message_queue_send_error{cluster=\"$fsp_namespace\"}[$__rate_interval]) * 120",
     "legendFormat": "MQ error"
    },
    {
     "expr": "rate(payment_processor_verifier_request_errors{cluster=\"$fsp_namespace\"}[$__rate_interval]) * 120",
     "legendFormat": "Verifier error"
    },
    {
     "expr": "rate(payment_processor_db_operation_error{cluster=\"$fsp_namespace\"}[$__rate_interval]) * 120",
     "legendFormat": "DB"
    }
   ]
  }
 ]
}