{
 "title": "SCS",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total SCS requests per 5 min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/5min" } },
   "targets": [
    {
     "expr": "sum(rate(smartcard_service_requests_total{container=~\"smartcard-service\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Payment total time (avg latency)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(smart_card_service_successful_payment_total_time_sum{container=~\"smartcard-service\"}[5m])) by (namespace)\n/ avg(rate(smart_card_service_successful_payment_total_time_count{container=~\"smartcard-service\"}[5m])) \nby (namespace)\n",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "DB Connection Status",
   "type": "timeseries",
   "description": "Status of the connection to DB (1 = connected, 0 = disconnected)",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(db_connection_status{container=~\"smartcard-service\"}) by (namespace)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "DB Health Check Errors",
   "type": "timeseries",
   "description": "Shows the number of DB health check failures over the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(db_health_check_errors_total[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " DB average time per operation ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(smart_card_service_db_operation_duration_sum[3m])) by (tx,namespace) /\nsum(rate(smart_card_service_db_operation_duration_count[3m])) by (tx,namespace)",
     "legendFormat": "{{namespace}}_{{tx}}"
    }
   ]
  },
  {
   "title": "HTTP requests with 400 or 500 response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(smartcard_service_requests_total{code=~\"4..|5..\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SCS request latency(avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(smartcard_service_request_duration_sum[5m])) by (namespace,route)\n/ avg(rate(smartcard_service_request_duration_count[5m])) \nby (namespace,route)",
     "legendFormat": "{{namespace}}{{route}}"
    }
   ]
  },
  {
   "title": "SCS request latency(90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(smartcard_service_request_duration_bucket[5m])) by (le, namespace,route))\n",
     "legendFormat": "{{namespace}}{{route}}"
    }
   ]
  },
  {
   "title": "SCS request latency(99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(smartcard_service_request_duration_bucket[5m])) by (le, namespace,route))\n",
     "legendFormat": "{{namespace}}{{route}}"
    }
   ]
  },
  {
   "title": "SCS Database Avg latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(smart_card_service_db_operation_duration_sum[5m])) by (namespace)\n/ avg(rate(smart_card_service_db_operation_duration_count[5m]))by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "SCS Database 90th percentile latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(smart_card_service_db_operation_duration_bucket[5m])) by (le, namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SCS Database 99th percentile latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(smart_card_service_db_operation_duration_bucket[5m])) by (le, namespace))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage rate over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{container=~\"smartcard-service\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"smartcard-service-.*\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Go routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(go_goroutines{container=~\"smartcard-service\"}) by (namespace)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open file descriptors ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(process_open_fds{container=~\"smartcard-service\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(process_network_transmit_bytes_total{container=~\"smartcard-service\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(process_network_receive_bytes_total{container=~\"smartcard-service\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}