{
 "title": "Filia System",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "payment_processor",
    "query": {
     "query": "label_values(kube_namespace_labels{namespace=~'payment-processor.*'}, namespace)"
    }
   },
   {
    "name": "env_currency_factor",
    "query": {
     "query": "label_values(env_info, currency_factor)"
    }
   },
   {
    "name": "env_currency_iso",
    "query": {
     "query": "label_values(env_info, currency_iso)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "env_info", "legendFormat": "{{ title }}" }
   ]
  },
  { "title": "Verifier Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Number (since last reset)",
   "type": "stat",
   "description": "Shows the total number of verifier commands (create, destroy, split, merge, switch) since the last restart. After a restart the number is reset to 0 as it is only stored in memory.\nTotal Value",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(command) (verifier_commands_count{command=~\".*v2\", instance=~\".*\"})",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Verifier Commands",
   "type": "graph",
   "description": "This panel shows how many commands are executed each minute.\nThe bars for the different commands are stacked.",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (rate(verifier_commands_count[$__rate_interval])) * 120",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Total Value, $env_currency_iso (since last reset)",
   "type": "stat",
   "description": "Similar to \"Total Number\" this only shows values since the last restart. The value is calculated as follows:\n\n- Create: Value of created note\n- Destroy: Value of destroyed note\n- Merge: Value of target note\n- Split: Value of source note\n- Switch: Value of switched note\n\nThe value is divided by the currency factor to show the amount in the main (bigger) currency unit.",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (command) (verifier_commands_value{command!=\"xxcreate_v2\"}) / $env_currency_factor",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "description": "Shows which percentage of response times were below certain threshold values.",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(verifier_request_duration_bucket{le=\"0.2\", route=~\".*api.*\"}[$__range])) / sum(rate(verifier_request_duration_bucket{le=\"+Inf\", route=~\".*api.*\"}[$__range]))",
     "legendFormat": "< 200ms"
    },
    {
     "expr": "sum(rate(verifier_request_duration_bucket{le=\"0.5\", route=~\".*api.*\"}[$__range])) / sum(rate(verifier_request_duration_bucket{le=\"+Inf\", route=~\".*api.*\"}[$__range]))",
     "legendFormat": "< 500ms"
    },
    {
     "expr": "sum(rate(verifier_request_duration_bucket{le=\"1\", route=~\".*api.*\"}[$__range])) / sum(rate(verifier_request_duration_bucket{le=\"+Inf\", route=~\".*api.*\"}[$__range]))",
     "legendFormat": "< 1 sec."
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Verifier Ressource Usage",
   "type": "graph",
   "description": "The graph shows the CPU usage and memory usage of the verifier. When CPU usage is close to 100%, the verifiers compute ressources are fully used. Memory usage should typically be below 100MiB, the limit is at around 8GiB.\n",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container=\"verifier\"}[$__rate_interval]))  / max(machine_cpu_cores)  ",
     "legendFormat": "CPU percentage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"core\", container=\"verifier\"}) by (container)",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Verifier Network Traffic",
   "type": "graph",
   "description": "This graph shows how much data was received and sent by the verifier. This includes traffic from and to verifier clients and traffic between the verifier and the database. The limit on Azure should be around 125MB/s.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"verifier-[^t].*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"verifier-[^t].*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Verifier Throughput",
   "type": "graph",
   "description": "This panel shows how many commands are executed per second.\nThe areas for the different commands are stacked.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "si:op/s" } },
   "yaxes": [
    { "format": "si:op/s" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (rate(verifier_commands_count[$__rate_interval]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Verifier Response Times",
   "type": "graph",
   "description": "Shows response time percentiles over time. For example, a 90% line at 500ms indicates that 90% of requests took less than 500ms.\n\nThe percentile numbers are only an estimate. Since we cannot store the response time of each request, we only count the response time in different buckets (e.g. count number of requests with less than 100ms and number with less than 200ms). From this, the percentiles are estimated.\n",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n    0.90, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n    0.50, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}