{
 "title": "Trivy Operator Dashboard",
 "description": "This Dashboard is used to visualise the metrics from the security reports of the Trivy Operator",
 "tags": [
  "trivy",
  "trivy operator",
  "security",
  "security scanning",
  "vulnerabilities",
  "exposed secrets",
  "misconfiguration"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=~\".*-base-infra-trivy-operator\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number and Type of Security Issues",
   "type": "stat",
   "description": "Total number by type of security issues identified in the cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\"})",
     "legendFormat": "Vulnerabilities"
    },
    {
     "expr": "sum(trivy_resource_configaudits{cluster=\"$cluster\"})",
     "legendFormat": "Misconfiguration"
    },
    {
     "expr": "sum(trivy_image_exposedsecrets{cluster=\"$cluster\"})",
     "legendFormat": "Exposed Secrets"
    },
    {
     "expr": "sum(trivy_clusterrole_clusterrbacassessments{cluster=\"$cluster\"})",
     "legendFormat": "RBAC Assessment"
    }
   ]
  },
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Workload: details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Severity Breakdown of all Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\", cluster=\"$cluster\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\", cluster=\"$cluster\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\", cluster=\"$cluster\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\", cluster=\"$cluster\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\", cluster=\"$cluster\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Number of Vulnerabilities by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerability by Image",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\", cluster=\"$cluster\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\", cluster=\"$cluster\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\", cluster=\"$cluster\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\", cluster=\"$cluster\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\", cluster=\"$cluster\"}) by (image_repository,image_tag)"
    }
   ]
  },
  {
   "title": "Vulnerability by Image",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "trivy_vulnerability_id{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Misconfiguration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Severity Breakdown of all Misconfiguration",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_resource_configaudits{severity=\"Critical\", cluster=\"$cluster\"})",
       "legendFormat": "Critical"
      },
      {
       "expr": "sum(trivy_resource_configaudits{severity=\"High\", cluster=\"$cluster\"})",
       "legendFormat": "High"
      },
      {
       "expr": "sum(trivy_resource_configaudits{severity=\"Medium\", cluster=\"$cluster\"})",
       "legendFormat": "Medium"
      },
      {
       "expr": "sum(trivy_resource_configaudits{severity=\"Low\", cluster=\"$cluster\"})",
       "legendFormat": "Low"
      }
     ]
    }
   ]
  },
  {
   "title": "RBAC Assessment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Severity Breakdown of RBAC Security Issues",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_role_rbacassessments{severity=\"Critical\", cluster=\"$cluster\"})",
       "legendFormat": "Critical"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{severity=\"High\", cluster=\"$cluster\"})",
       "legendFormat": "High"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{severity=\"Medium\", cluster=\"$cluster\"})",
       "legendFormat": "Medium"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{severity=\"Low\", cluster=\"$cluster\"})",
       "legendFormat": "Low"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{severity=\"UNKNOWN\", cluster=\"$cluster\"})",
       "legendFormat": "Unknown"
      }
     ]
    }
   ]
  },
  {
   "title": "Exposed Secrets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exposed Secrets per namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(trivy_image_exposedsecrets{cluster=\"$cluster\"}) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}