{
 "title": "Verifier Benchmark",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Benchmark Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operations per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(filia_verifier_go_load_tests_operation_count[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum without (container,job,operation)(irate(filia_verifier_go_load_tests_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum without (container,job,operation)(irate(filia_verifier_go_load_tests_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n    0.9, \n    sum without (container,job,operation)(irate(filia_verifier_go_load_tests_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "90%"
    },
    {
     "expr": "sum without (instance,operation) (irate(filia_verifier_go_load_tests_request_duration_sum[$__rate_interval])) / \nsum without (instance,operation)(irate(filia_verifier_go_load_tests_request_duration_count[$__rate_interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Number of simulated clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filia_verifier_go_load_tests_num_clients",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Verifier Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operations per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (rate(verifier_commands_count[$__rate_interval]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Response time (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n    0.9, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n    0.5, \n    sum without (instance,route)(irate(verifier_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "50%"
    },
    {
     "expr": "sum(irate(verifier_request_duration_sum{route!=\"metricsPath\"}[$__rate_interval])) / sum(irate(verifier_request_duration_count{route!=\"metricsPath\"}[$__rate_interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(verifier_request_duration_sum{route!=\"metricsPath\"}[$__rate_interval]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Ressources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"core\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"core\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} transmit"
    }
   ]
  },
  {
   "title": "Database Response Times",
   "type": "graph",
   "description": "This panel shows how long transactions take at the database layer.",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum without (container,job,operation)(irate(verifier_db_transaction_duration_bucket[$__rate_interval])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum without (container,job,operation)(irate(verifier_db_transaction_duration_bucket[$__rate_interval])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n    0.90, \n    sum without (container,job,operation)(irate(verifier_db_transaction_duration_bucket[$__rate_interval])))",
     "legendFormat": "90%"
    },
    {
     "expr": "sum without (instance,operation) (irate(verifier_db_transaction_duration_sum[$__rate_interval])) / \nsum without (instance,operation)(irate(verifier_db_transaction_duration_count[$__rate_interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "CPU usage in percent.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"verifier\"}[$__rate_interval]))",
     "legendFormat": "verifier"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"verifier-test\"}[$__rate_interval])",
     "legendFormat": "verifier-test"
    }
   ]
  },
  {
   "title": "Transaction Statistics",
   "type": "graph",
   "description": "Under normal load there should be 0 transaction retries and 1 operation per transaction. When the system runs out of available database connections, there will be more than one operation per transaction.\nThis is a hint for increasing the number of connections.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(verifier_db_transaction_size[$__rate_interval])) / sum(rate(verifier_db_transaction_duration_count[$__rate_interval]))",
     "legendFormat": "operations per transaction"
    },
    {
     "expr": "rate(verifier_db_transaction_tries[$__rate_interval])",
     "legendFormat": "transaction retries"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"core\", container!=\"POD\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(filia_verifier_go_load_tests_error_count[$__rate_interval]))",
     "legendFormat": "{{operation}} benchmark errors"
    },
    {
     "expr": "sum by (operation) (rate(verifier_commands_err_count[$__rate_interval]))",
     "legendFormat": "{{operation}} verifier errors"
    }
   ]
  }
 ]
}