apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: postgresql
    repoURL: "registry-1.docker.io/bitnamicharts"
    targetRevision: "16.3.2" #to be updated 16.7.20
    helm:
      releaseName: "postgresql"
      values: |
        global:
          defaultStorageClass: premium2-disk-sc
        auth:
          existingSecret: "postgres-credentials"
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus
        primary:
          configuration: |
            listen_addresses = '*'
            port = '5432'
            max_wal_size = '400MB'
            min_wal_size = '128MB'
            log_connections = 'false'
            log_disconnections = 'false'
            log_hostname = 'false'
            client_min_messages = 'error'
            max_connections = {{ .Values.postgres.config.maxConnections }} 
            shared_buffers = 256MB
            work_mem = 4MB
            maintenance_work_mem = 64MB
            temp_buffers = 8MB
            effective_cache_size = 256MB
            fsync = 'on'
            full_page_writes = 'on'
            wal_level = 'minimal'
            max_wal_senders = '0'
            max_worker_processes = '4'
          persistence:
            enabled: true
            storageClass: premium2-disk-sc
            size: 64Gi
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true