apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  namespace: frontend
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: test Project
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - git@github.com:moaaznoaman/argocd.git
    - git@github.com:moaaznoaman/argocd-variables.git
    - git@github.com:moaaznoaman/argocd-variables-new.git