apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pods-appset
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            env: "dev"
#    - git:
#        repoURL: https://github.com/moaaznoaman/argocd-variables.git
#        revision: HEAD
#        directories:
#          - path: environments/*
#          matchExpressions:
#            - {
#              key: "name",
#              operator: In,
#              values: ["vcluster2"],
#            }
#     - list:
#         elements:
#           - chartName: "podschart"

  template:
    metadata:
      name: "pods-{{.name}}"
      namespace: argocd
      labels:
        env: "pods"
        app: "infra"
        # prod: "true"
        # envType: "{{ .metadata.labels.env_type }}"
    spec:
      project: infra
      sources:
        - repoURL: git@github.com:moaaznoaman/argocd-variables.git
          targetRevision: HEAD
          ref: values
        - repoURL: git@github.com:moaaznoaman/argocd-variables-new.git
          targetRevision: HEAD
          ref: valuesnew
        - repoURL: git@github.com:moaaznoaman/argocd.git
          path: charts/pods
          targetRevision: HEAD
          helm:
            valueFiles:
              - "values.yaml"
              - "$values/environments/dev/values.yaml"
              - "$valuesnew/environments/dev/values.yaml"
      destination:
        name: "{{.name}}" # "{{ .metadata.labels.name }}" # https://kubernetes.default.svc
        namespace: "pods" #TODO: check this
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        #   - ServerSideApply=true # Big CRDs.
        #   - ApplyOutOfSyncOnly=true
        #   - preserveResourcesOnDeletion=true