apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pods-appset
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - {
                key: "name",
                operator: In,
                values: ["in-cluster"],
              }
  template:
    metadata:
      name: "{{ .metadata.labels.env }}-pods"
    spec:
      project: infra
      sources:
      - repoURL: git@github.com:moaaznoaman/argocd-variables.git
        targetRevision: HEAD  
        # targetRevision: "{{ .metadata.labels.environmentsBranch }}"
        ref: values
      - repoURL: git@github.com:moaaznoaman/argocd.git
        targetRevision: "HEAD" # "{{ .metadata.labels.gitopsBranch }}"
        path: "charts/pods"
        releaseName: "pods-test-helm"
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - "values.yaml"
            - "$values/environments/{{ .metadata.labels.env }}/values.yaml"
            # - "../../clusters/{{ .metadata.labels.suite }}/namespace-values.yaml"
            # - "$values/environments/{{ .metadata.labels.env }}/fsps/{{ .name }}/gitops/namespace-values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: helm-charts #TODO: check this
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true # Big CRDs.
          - ApplyOutOfSyncOnly=true
          - preserveResourcesOnDeletion=true