apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pods-appset
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - clusters:
                    selector:
                      matchExpressions:
                        - {
                            key: "env",
                            operator: In,
                            values: ["dev"],
                          }
                - git:
                    repoURL: git@github.com:moaaznoaman/argocd-variables.git
                    revision: HEAD
                    directories:
                      - path: environments/*
          - git:
              repoURL: git@github.com:moaaznoaman/argocd-variables.git
              revision: HEAD
              directories:
                - path: environments/*

    # - list:
    #     elements:
    #       - chartName: "podschart"

  template:
    metadata:
      name: "pods-{{.path.basename}}"
      namespace: argocd
      labels:
        env: "{{.path.basename}}"
        app: "infra"
        # prod: "true"
        # envType: "{{ .metadata.labels.env_type }}"
    spec:
      project: infra
      sources:
      - repoURL: git@github.com:moaaznoaman/argocd-variables.git
        targetRevision: HEAD
        ref: values
      - repoURL: git@github.com:moaaznoaman/argocd-variables-new.git
        targetRevision: HEAD
        ref: valuesnew  
      - repoURL: git@github.com:moaaznoaman/argocd.git
        path: charts/pods
        targetRevision: HEAD
        helm:
          valueFiles:
            - "values.yaml"
            - "$values/environments/{{.path.basename}}/values.yaml"
            - "$valuesnew/environments/{{.path.basename}}/values.yaml"
      destination:
        name: "{{ .metadata.labels.name }}" # https://kubernetes.default.svc
        namespace: "{{ .path.basename }}" #TODO: check this
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        #   - ServerSideApply=true # Big CRDs.
        #   - ApplyOutOfSyncOnly=true
        #   - preserveResourcesOnDeletion=true