apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pods-appset
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - {
                      key: "name",
                      operator: In,
                      values: ["in-cluster"],
                    }
          - git:
            repoURL: git@github.com:moaaznoaman/argocd.git
            revision: HEAD
            directories:
              - path: environments/*/*
    # - list:
    #     elements:
    #       - chartName: "podschart"
    # - git:
    #     repoURL: https://github.com/moaaznoaman/argocd.git
    #     revision: HEAD
    #     directories:
    #       # here it will read the paths under configs and the subpaths under the config paths
    #       - path: environments/*/*
  template:
    metadata:
      name: "podschart-{{path.basename}}"
      # namespace: argocd
    spec:
      project: default
      sources:
      - repoURL: git@github.com:moaaznoaman/argocd.git
        path: charts/pods
        targetRevision: HEAD
        helm:
          valueFiles:
            - "values.yaml"
            - "../../environments/{{path.basename}}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "podschart-{{path.basename}}" #TODO: check this
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        #   - ServerSideApply=true # Big CRDs.
        #   - ApplyOutOfSyncOnly=true
        #   - preserveResourcesOnDeletion=true