apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: online-appset
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/moaaznoaman/argocd.git
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: environments/*/*
    # - clusters:
    #     selector:
    #       matchExpressions:
    #         - {
    #             key: "name",
    #             operator: In,
    #             values: ["in-cluster"],
    #           }

  template:
    metadata:
      name: "{{path.basename}}-pods"
      namespace: argocd
    spec:
      project: default
      sources:
      - repoURL: https://github.com/moaaznoaman/argocd.git
        path: charts/onlinechart
        targetRevision: HEAD
        helm:
          valueFiles:
            - "environments/{{path.basename}}/values.yaml"
            - "charts/pods/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}" #TODO: check this
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        #   - ServerSideApply=true # Big CRDs.
        #   - ApplyOutOfSyncOnly=true
        #   - preserveResourcesOnDeletion=true