apiVersion: v1
kind: Namespace
metadata:
  name: tcp-monitoring
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-server
  namespace: tcp-monitoring
  labels:
    app: tcp-server
spec:
  containers:
    - name: tcp-server
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do echo "hello" | nc -l -p 4545; done
      ports:
        - containerPort: 4545
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server
  namespace: tcp-monitoring
  labels:
    monitor.tcp: "true"  # <-- so Blackbox picks it up
spec:
  selector:
    app: tcp-server
  ports:
    - port: 4545
      targetPort: 4545
      name: tcp