apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployments
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    directory:
      recurse: true
    path: deployments/
    repoURL: git@github.com:moaaznoaman/argocd.git
    targetRevision: HEAD
  destination:
    namespace: nginx-deployment
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  # info:
  #   - name: url
  #     value: https://argoproj.github.io/