apiVersion: v1
kind: Namespace
metadata:
  name: healthcheck
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app
  namespace: healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
        - name: app
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: health-app
  namespace: healthcheck
  annotations:
    blackbox.io/path: "/health"  # <-- important for Prometheus Blackbox discovery
  # labels:
  #   monitor.http: "true"
spec:
  selector:
    app: health-app
  ports:
    - port: 8080
      targetPort: 8080
