apiVersion: v1
kind: Namespace
metadata:
  name: healthcheck
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app
  namespace: healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
        - name: app
          image: nginxdemos/hello
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: health-app
  namespace: healthcheck
  annotations:
    blackbox.io/enabled: "true"
    blackbox.io/schema: "http"
    blackbox.io/path: "/"
    blackbox.io/port-name: "http"
  # labels:
  #   blackbox.io/path: "/health"
spec:
  selector:
    app: health-app
  ports:
    - port: 8080
      targetPort: 80
      name: http
