apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - { key: "cluster", operator: In, values: [ "vcluster2" ] }

  template:
    metadata:
      name: "hello-{{ .metadata.labels.env }}-{{.name}}"
      namespace: argocd
      labels:
        env: "{{ .metadata.labels.env }}"
        app: "infra"
    spec:
      project: infra
      sources:
        - repoURL: git@github.com:moaaznoaman/argocd.git
          path: charts/hello
          targetRevision: HEAD
          helm:
            valueFiles:
              - "values.yaml"
      destination:
        name: "{{.name}}" 
        namespace: "{{ .metadata.labels.env }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true