apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: app
          image: moazrefat/hello:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hello
  annotations:
    blackbox.io/enabled: "true"
    blackbox.io/schema: "http"
    blackbox.io/path: "/api/health"
    blackbox.io/port-name: "http"
  # labels:
  #   blackbox.io/path: "/health"
spec:
  selector:
    app: hello
  ports:
    - port: 8080
      targetPort: 8080
      name: http   
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: hello
  name: hello
spec:
  ingressClassName: public
  rules:
  - host: hello.cluster.local
    http:
      paths:
      - backend:
          service:
            name: hello
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific