apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: app1
  labels:
    monitor.http: "true"  # <-- important for Prometheus Blackbox discovery
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: app2
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   namespace: app2
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:1.25
#           ports:
#             - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   namespace: app2
#   labels:
#     monitor: "true"  # <-- important for Prometheus Blackbox discovery
# spec:
#   selector:
#     app: nginx
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       name: http
apiVersion: v1
kind: Namespace
metadata:
  name: app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 4545  # Container listens on 4545
          command: ["/bin/sh", "-c"]
          args:
            - |
              sed -i 's/80/4545/' /etc/nginx/conf.d/default.conf && \
              nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: app2
  labels:
    monitor.http: "true"  # Important for Prometheus Blackbox discovery
spec:
  selector:
    app: nginx
  ports:
    - port: 4545        # Service exposed on port 4545
      targetPort: 4545  # Must match containerPort
      protocol: TCP
      name: http
