apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-creds
  namespace: default
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: argocd-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret-local
    creationPolicy: 'Owner'
#    template:
#      data:
#        argocd-id: "{{ .QaArgocdClientId }}"
  dataFrom:
    - find:
        name:
          regexp: ".*QaArgocdClientId"
    - find:
        name:
          regexp: ".*QaArgocdClientSecret"

#  data:
#    - secretKey: password
#      remoteRef:
#        key: mypassword/
#        property: key
# dataFrom:
#    - extract:
#        key: test-eso/test-secret